# Path to oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"

# asdf
source '/opt/homebrew/opt/asdf/libexec/asdf.sh'
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

# Disable default theme for Oh My Zsh
ZSH_THEME=""

# Configure oh-my-zsh plugins
plugins=(
    asdf
#    git
#    docker
#    docker-compose
#    kubectl
)

source $ZSH/oh-my-zsh.sh

# User configuration
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='nvim'
export VISUAL='nvim'

# Initialize Starship
eval "$(starship init zsh)"

# Source Homebrew-installed plugins
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.shell_tools_config

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(zoxide init zsh)"
export PATH="$HOME/.local/bin:$PATH"

# Golang environment setup
. ${ASDF_DATA_DIR:-$HOME/.asdf}/plugins/golang/set-env.zsh

# YourCoach
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools
alias mongo-b2b-prod="ssh yc-b2b-mongo-prod -N -L 27018:localhost:27017"
alias mongo-b2b-stage="ssh yc-b2b-mongo-stage -N -L 27020:localhost:27017"
alias mongo-b2b-dev="ssh yc-b2b-mongo-dev -N -L 27019:localhost:27017"
